
export const LOVE_MESSAGES = [
  "Because you make ordinary days magical.",
  "Because your smile fixes my worst moods.",
  "Because you are soft but strong.",
  "Because you try your best at everything.",
  "Because badminton with you is my favorite therapy.",
  "Because 2022 was the year destiny chose me.",
  "Because you care deeply, even when work is hard.",
  "Because you feel like home.",
  "Because you believe in us.",
  "Because your hugs feel like peace.",
  "Because I see my future in your eyes.",
  "Because you are my Murugesa.",
  "Because you are stronger than your toughest days.",
  "Because you make me want to be better.",
  "Because I choose you. Every single day.",
  "Because you make simple moments unforgettable.",
  "Because your laugh is my favorite sound.",
  "Because you make love feel safe.",
  "Because you are my calm in chaos.",
  "Because you glow differently when you smile.",
  "Because you make bad days survivable.",
  "Because your happiness matters to me more than mine.",
  "Because you are the kindest soul I know.",
  "Because you make my heart feel understood.",
  "Because loving you feels natural.",
  "Because your presence makes everything better.",
  "Because you look adorable when you're focused.",
  "Because you inspire me without even trying.",
  "Because you are my favorite hello.",
  "Because you are my hardest goodbye.",
  "Because your eyes tell stories I want to read forever.",
  "Because you make me believe in destiny.",
  "Because you feel like my answered prayer.",
  "Because you care deeply, even when it hurts.",
  "Because you make me proud every single day.",
  "Because you are stronger than you think.",
  "Because you never give up.",
  "Because you try again even when things are hard.",
  "Because you deserve the softest kind of love.",
  "Because your hugs reset my entire world.",
  "Because you look beautiful even when you don’t try.",
  "Because you make 2022 the best year of my life.",
  "Because Grenoble became magical the day I met you.",
  "Because you make ordinary streets feel romantic.",
  "Because you trust me with your thoughts.",
  "Because you share your dreams with me.",
  "Because you make the future feel exciting.",
  "Because you make me want to grow.",
  "Because your hand fits perfectly in mine.",
  "Because your good morning texts change my mood instantly.",
  "Because you make distance feel small.",
  "Because you are patient with me.",
  "Because you forgive easily.",
  "Because you are gentle but powerful.",
  "Because you turn stress into strength.",
  "Because even when you complain about your manager, you still handle things gracefully.",
  "Because you deserve peace after long days.",
  "Because you are braver than you realize.",
  "Because you make love look effortless.",
  "Because you understand me without explanations.",
  "Because you listen. Truly listen.",
  "Because you make inside jokes with me.",
  "Because badminton with you feels like a date every time.",
  "Because you look cutest when you’re competitive.",
  "Because you celebrate small wins.",
  "Because you never stop caring.",
  "Because you are thoughtful in little ways.",
  "Because you remember things that matter.",
  "Because you check if I reached home safely.",
  "Because you make me feel chosen.",
  "Because you are my favorite distraction.",
  "Because you are my favorite priority.",
  "Because you make time slow down.",
  "Because you make my heart race in the best way.",
  "Because you are the softness my life needed.",
  "Because you are my lucky charm since 2022.",
  "Because you are worth every effort.",
  "Because you make love feel peaceful, not dramatic.",
  "Because you are beautifully imperfect.",
  "Because you make my world brighter just by existing.",
  "Because you bring warmth into cold days.",
  "Because you make tough weeks easier.",
  "Because you are incredibly lovable.",
  "Because you deserve someone who sees your worth.",
  "Because you make my heart feel safe to open.",
  "Because you give me butterflies even now.",
  "Because you are my comfort place.",
  "Because your smile is contagious.",
  "Because you make love feel like friendship too.",
  "Because you stand tall even when tired.",
  "Because you shine without needing attention.",
  "Because you make me feel proud to call you mine.",
  "Because you make plans exciting.",
  "Because you are the best part of my routine.",
  "Because you make every week better.",
  "Because you care about people deeply.",
  "Because you are emotionally strong.",
  "Because you make vulnerability beautiful.",
  "Because you make commitment feel easy.",
  "Because you are worth choosing every day.",
  "Because you are my peace after a long day.",
  "Because you are my happiness in human form.",
  "Because you are my favorite chapter.",
  "Because you are my forever teammate.",
  "Because loving you feels like the right decision.",
  "Because you are my Murugesa.",
  "Because my life feels better with you in it.",
  "Because every version of my future has you.",
  "Because you are not just part of my story — you are my story."
];

export const TIMELINE_DATA = [
  {
    title: "Grenoble & Alésia – Where it Began",
    text: "I remember when we first started talking as friends. Meeting you for the first time changed everything. I used to find every excuse to come and drop you home, just to steal a few more minutes with you."
  },
  {
    title: "Argenteuil – Our First Home",
    text: "This is where we started living together for the first time. I can never forget the small romances and those beautiful initial days of our relationship that felt like a dream."
  },
  {
    title: "Asnières-sur-Seine – The Studio",
    text: "Living in that tiny studio apartment taught us so much. We started having our first real fights, but we never stopped talking, even for a single day. We chose to stick together."
  },
  {
    title: "La Défense – Growing Together",
    text: "Our challenges grew, but so did our love. We found ways to solve our problems and change for the better because of the love we share. This is where we took the giant step of telling our parents about us."
  },
  {
    title: "Wherever We Go Next...",
    text: "We have already crossed our most difficult times together. Wherever the journey takes us next, I know we will only make this relationship happier and stronger. You are my forever teammate."
  }
];
